/**
 * AI draft — opens the "Draft with AI" dialog on the project backlog and
 * verifies that the drafted issue list renders.
 *
 * To keep the suite hermetic (no live OpenAI calls), we install a Playwright
 * route handler that intercepts `/api/ai/draft-issues` and returns a stubbed
 * payload matching the route's response shape. This verifies the client flow;
 * provider/route integration requires a separate controlled-environment test.
 */
import { test, expect } from '@playwright/test';
import { ensureSeed } from './fixtures/seed';

test.describe('ai draft', () => {
  test('drafts issues from a prompt and shows them in the dialog', async ({ page }) => {
    // A cold Next.js development server may need to compile the backlog and
    // its data routes before the hydrated action becomes available.
    test.setTimeout(90_000);
    const seed = await ensureSeed();

    // Intercept the AI endpoint with a deterministic response.
    await page.route('**/api/ai/draft-issues', async (route) => {
      const stub = {
        drafts: [
          {
            type: 'task',
            title: 'Stubbed AI draft: add login analytics',
            description: 'Generated by Playwright stub for ai-draft.spec',
            priority: 'high',
            labels: ['ai-stub'],
            estimate: 3,
          },
          {
            type: 'bug',
            title: 'Stubbed AI draft: fix sign-in retry',
            description: 'Generated by Playwright stub for ai-draft.spec',
            priority: 'critical',
            labels: ['ai-stub'],
            estimate: 2,
          },
        ],
        provider: 'playwright-stub',
      };
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(stub),
      });
    });

    // Also stub the capability check so the button renders even if the
    // workspace has no real provider configured.
    await page.route('**/api/ai/capability**', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          canDraft: true,
          provider: 'playwright-stub',
          model: 'stub',
        }),
      });
    });

    await page.goto(`/projects/${seed.projectId}/backlog`);

    const draftBtn = page.getByRole('button', { name: /draft with ai/i });
    await expect(draftBtn).toBeVisible({ timeout: 45_000 });
    await draftBtn.click();

    const dialog = page.getByRole('dialog');
    await expect(dialog).toBeVisible();

    // The dialog has a prompt textarea + a generate button. Selectors are
    // intentionally lenient — we match by accessible name.
    const promptField = dialog.getByRole('textbox').first();
    await promptField.fill('Add login analytics and fix retry bug');

    const generateBtn = dialog.getByRole('button', {
      name: /generate|draft|create/i,
    });
    await generateBtn.first().click();

    // The stubbed draft titles should appear in the dialog.
    await expect(dialog.getByRole('textbox', { name: /draft 1 title/i })).toHaveValue(
      /stubbed ai draft: add login analytics/i,
      { timeout: 10_000 }
    );
    await expect(dialog.getByRole('textbox', { name: /draft 2 title/i })).toHaveValue(
      /stubbed ai draft: fix sign-in retry/i
    );
  });
});
