CREATE INDEX IF NOT EXISTS "org_member_user_idx" ON "organization_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "org_member_organization_idx" ON "organization_members" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_member_user_idx" ON "team_members" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_member_team_idx" ON "team_members" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "team_organization_idx" ON "teams" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_organization_idx" ON "projects" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_team_idx" ON "projects" USING btree ("team_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_status_idx" ON "projects" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_lead_idx" ON "projects" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_user_idx" ON "issue_activities" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_type_idx" ON "issue_activities" USING btree ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_created_at_idx" ON "issue_activities" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_issue_created_at_idx" ON "issue_activities" USING btree ("issue_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "comment_created_at_idx" ON "issue_comments" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "comment_issue_created_at_idx" ON "issue_comments" USING btree ("issue_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_reporter_idx" ON "issues" USING btree ("reporter_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_priority_idx" ON "issues" USING btree ("priority");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_type_idx" ON "issues" USING btree ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_created_at_idx" ON "issues" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_updated_at_idx" ON "issues" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_project_status_idx" ON "issues" USING btree ("project_id","status_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_project_sprint_idx" ON "issues" USING btree ("project_id","sprint_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "issue_project_assignee_idx" ON "issues" USING btree ("project_id","assignee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sprint_project_idx" ON "sprints" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sprint_status_idx" ON "sprints" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sprint_project_status_idx" ON "sprints" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sprint_date_range_idx" ON "sprints" USING btree ("start_date","end_date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_user_idx" ON "audit_logs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_organization_idx" ON "audit_logs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_resource_type_idx" ON "audit_logs" USING btree ("resource_type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_resource_id_idx" ON "audit_logs" USING btree ("resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_project_idx" ON "audit_logs" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_issue_idx" ON "audit_logs" USING btree ("issue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_created_at_idx" ON "audit_logs" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_org_created_at_idx" ON "audit_logs" USING btree ("organization_id","created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_resource_idx" ON "audit_logs" USING btree ("resource_type","resource_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_delivery_webhook_idx" ON "webhook_deliveries" USING btree ("webhook_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_delivery_status_idx" ON "webhook_deliveries" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_delivery_created_at_idx" ON "webhook_deliveries" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_delivery_webhook_status_idx" ON "webhook_deliveries" USING btree ("webhook_id","status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_organization_idx" ON "webhooks" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_project_idx" ON "webhooks" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_active_idx" ON "webhooks" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_org_active_idx" ON "webhooks" USING btree ("organization_id","is_active");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "watcher_user_idx" ON "watchers" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "watcher_issue_idx" ON "watchers" USING btree ("issue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "watcher_project_idx" ON "watchers" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_user_idx" ON "saved_filters" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_organization_idx" ON "saved_filters" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_project_idx" ON "saved_filters" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_public_idx" ON "saved_filters" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_starred_idx" ON "saved_filters" USING btree ("is_starred");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_user_starred_idx" ON "saved_filters" USING btree ("user_id","is_starred");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "saved_filter_org_public_idx" ON "saved_filters" USING btree ("organization_id","is_public");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "search_history_user_idx" ON "search_history" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "search_history_organization_idx" ON "search_history" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "search_history_project_idx" ON "search_history" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "search_history_created_at_idx" ON "search_history" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "search_history_user_created_at_idx" ON "search_history" USING btree ("user_id","created_at");