-- Standups: per-user daily digest of work activity for the previous 24h.
-- Generated by cron (POST /api/cron/standup) or on demand
-- (POST /api/users/me/standup/preview). One row per (user, org, date).
-- `content_md` is the LLM-rendered markdown shown on the dashboard;
-- `source_events` keeps the raw inputs for re-summarization / audit.

CREATE TABLE IF NOT EXISTS "standups" (
  "id" text PRIMARY KEY NOT NULL,
  "user_id" text NOT NULL,
  "organization_id" text NOT NULL,
  "date" varchar(10) NOT NULL,
  "content_md" text NOT NULL,
  "blockers_md" text NOT NULL DEFAULT '',
  "source_events" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "created_at" timestamp DEFAULT now() NOT NULL
);

DO $$
BEGIN
  ALTER TABLE "standups"
    ADD CONSTRAINT "standups_user_id_users_id_fk"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE "standups"
    ADD CONSTRAINT "standups_organization_id_organizations_id_fk"
    FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "standups_user_org_date_idx"
  ON "standups" USING btree ("user_id", "organization_id", "date");

CREATE INDEX IF NOT EXISTS "standups_user_idx"
  ON "standups" USING btree ("user_id");

CREATE INDEX IF NOT EXISTS "standups_organization_idx"
  ON "standups" USING btree ("organization_id");
