// Export all schema tables
export * from './organizations';
export * from './users';
export * from './projects';
export * from './permission-schemes';
export * from './issue-security';
export * from './issues';
export * from './workflows';
export * from './sprints';
export * from './attachments';
export * from './notifications';
export * from './custom-fields';
export * from './audit-logs';
export * from './documents';
export * from './collab-documents';
export * from './chat';
export * from './api-keys';
export * from './webhooks';
export * from './watchers';
export * from './email-templates';
export * from './notification-preferences';
export * from './saved-filters';
export * from './search-history';
export * from './push-subscriptions';
export * from './system';
export * from './agents';
export * from './agent-approvals';
export * from './project-templates';
export * from './semantic-search';
export * from './resource-management';
export * from './integration-connections';
export * from './password-reset-tokens';
export * from './email-verification-tokens';
export * from './user-appearance';
export * from './project-modules';
export * from './pinned-items';
export * from './automation-executions';
export * from './drafts';
export * from './integration-client-credentials';
export * from './audit-log-sinks';

// 2026 roadmap additions
export * from './agent-sessions';
export * from './ai-cost-guard';
export * from './ai-disclosures';
export * from './import-jobs';
export * from './initiatives';
export * from './intake-forms';
export * from './issue-status-history';
export * from './issue-triage-suggestions';
export * from './llm-batch-jobs';
// llm-call-audit table is defined in ./ai-cost-guard (consolidated)
export * from './slack';
export * from './sso';
export * from './standups';
export * from './time-entries';

// Jira-parity structural layer (2026-06)
export * from './labels';
export * from './versions';
export * from './components';
